[package]
name = "rustlings"
version = "0.1.0"
authors = ["olivia <olivia@fastmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
indicatif = "0.9.0"
console = "0.6.2"
syntect = "3.0.2"
notify = "4.0.0"
