language: rust

branches:
  only:
  - master

cache:
  cargo: true

script:
  - cargo run --bin generate_readme
  - git config user.name "Carol (Nichols || Goulding)"
  - git config user.email "carol.nichols@gmail.com"
  - git commit -am "Regenerate README" && git remote add upstream "https://$GH_TOKEN@github.com/carols10cents/rustlings.git" && git push -q upstream HEAD:master > /dev/null 2>&1 || true

notifications:
  email:
    on_success: never

